name: catty-reminders

services:
  app:
    image: ghcr.io/me1ax/catty-reminders-app:latest
    ports:
      - "8181:8181"
    environment:
      - DEPLOY_REF=${DEPLOY_REF:-NA}
    volumes:
      - app-data:/app/data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: mypass
      MARIADB_DATABASE: catty_reminders
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  app-data:
  mysql-data:
