name: catty-reminders

services:
  app:
    image: ghcr.io/me1ax/catty-reminders-app:latest
    ports:
      - "8181:8181"
    environment:
      - DEPLOY_REF=${DEPLOY_REF:-NA}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: mypass
      MARIADB_DATABASE: catty_reminders
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
